
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class MvIcons {
 const  MvIcons._();
  static const String _fontFamily = 'mvIcon';
  static const IconData arrowBack = Icons.arrow_back;
  static const IconData arrowDown = IconData(0xe901, fontFamily: _fontFamily);
  static const IconData arrowForward = Icons.arrow_forward;
  static const IconData arrowForwardIos =CupertinoIcons.forward;
  static const IconData scan = IconData(0xe904, fontFamily: _fontFamily);
  static const IconData cancelOutlined = IconData(0xe905, fontFamily: _fontFamily);
  static const IconData checked = IconData(0xe906, fontFamily: _fontFamily);
  static const IconData checkedOutlined = IconData(0xe907, fontFamily: _fontFamily);
  static const IconData circle = IconData(0xe908, fontFamily: _fontFamily);
  static const IconData delete = IconData(0xe909, fontFamily: _fontFamily);
  static const IconData edit = IconData(0xe90a, fontFamily: _fontFamily);
  static const IconData favorite = IconData(0xe90b, fontFamily: _fontFamily);
  static const IconData history = Icons.history_sharp;
  static const IconData favoriteOutlined = IconData(0xe90c, fontFamily: _fontFamily);
  static const IconData news = IconData(0xe90d, fontFamily: _fontFamily);
  static const IconData home = IconData(0xe90e, fontFamily: _fontFamily);
  static const IconData fire = IconData(0xe90f, fontFamily: _fontFamily);
  static const IconData radioButton = IconData(0xe910, fontFamily: _fontFamily);
  static const IconData restart = IconData(0xe912, fontFamily: _fontFamily);
  static const IconData search = CupertinoIcons.search;
  static const IconData settings = IconData(0xe914, fontFamily: _fontFamily);
  static const IconData shoppingOutlined = IconData(0xe915, fontFamily: _fontFamily);
  static const IconData shopping = IconData(0xe916, fontFamily: _fontFamily);
  static const IconData starOutlined = IconData(0xe917, fontFamily: _fontFamily);
  static const IconData star = IconData(0xe918, fontFamily: _fontFamily);
  static const IconData translation = IconData(0xe91a, fontFamily: _fontFamily);
  static const IconData user = IconData(0xe91b, fontFamily: _fontFamily);
  static const IconData visibility = IconData(0xe91c, fontFamily: _fontFamily);
  static const IconData visibilityOff = IconData(0xe91d, fontFamily: _fontFamily);
  static const IconData key = IconData(0xe91e, fontFamily: _fontFamily);
  static const IconData close = IconData(0xe91f, fontFamily: _fontFamily);
  static const IconData store = Icons.store;
  static  const  IconData payments = Icons.payments;
  static  const  IconData sort = CupertinoIcons.sort_down;
  static  const  IconData filter = Icons.filter_alt;
  static  const  IconData brokenImage = Icons.broken_image;
  static const  IconData error = Icons.error;
  static const  IconData warning = Icons.warning;
  static const  IconData verified = Icons.verified;
  static const  IconData lock = Icons.lock;
  static const  IconData share = Icons.share;
  static const  IconData email = CupertinoIcons.mail_solid;
  static const  IconData call = CupertinoIcons.phone_fill;
  static const  IconData calender = CupertinoIcons.calendar;
  static const  IconData locationCity = CupertinoIcons.house_alt_fill;
  static const  IconData remove = CupertinoIcons.minus;
  static const  IconData add = CupertinoIcons.add;
  static const  IconData gallery = CupertinoIcons.photo_fill_on_rectangle_fill;
  static const  IconData camera = CupertinoIcons.photo_camera_solid;
  static const  IconData refresh = CupertinoIcons.refresh;
  static const  IconData delivery = Icons.delivery_dining_rounded;
  static const  IconData shipping = Icons.local_shipping;
  static const IconData timelapse = CupertinoIcons.timer_fill ;
  static const IconData login = Icons.login ;
  static const IconData logout = Icons.logout ;
  static const IconData starHalf = Icons.star_half ;
  static const IconData support = Icons.support_agent ;
  static const IconData checkedCircle = Icons.check_circle_sharp ;
}
